# Makefile

all: main.pdf

diff: main-diff.pdf

main.pdf: main.tex main.bib Makefile
	pdflatex main
	bibtex main
	pdflatex main
	pdflatex main

main-diff.pdf: main.tex main.bib Makefile
	echo "% don't edit this file (generated by latexdiff)" > main-diff.tex
	latexdiff main-submitted.tex main.tex >>main-diff.tex
	pdflatex main-diff
	bibtex main-diff
	pdflatex main-diff
	pdflatex main-diff

clean:
	rm -rf *~ *.log *.aux *.blg *.bbl

# eof
