# Makefile

all: main.pdf

diff: main-diff.pdf

diff2: main-cft.tex
	echo "% don't edit this file (generated by latexdiff)" > main-diff2.tex
	latexdiff main.tex main-cft.tex >>main-diff2.tex
	pdflatex main-diff2
	bibtex main-diff2
	pdflatex main-diff2
	pdflatex main-diff2

main.pdf: main.tex main.bib Makefile
	pdflatex main
	bibtex main
	pdflatex main
	pdflatex main

main-diff.pdf: main.tex main.bib Makefile
	echo "% don't edit this file (generated by latexdiff)" > main-diff.tex
	latexdiff main-submitted.tex main.tex | grep -v CCSXML | grep -v '<concept' | grep -v 'concept>' | grep -v 'ccs2012' | sed -e 's/section{\\DIFdel/section{\\textcolor{red}/g' | sed -e 's/section{\\DIFadd/section{\\textcolor{blue}/g' >>main-diff.tex
	pdflatex main-diff
	bibtex main-diff
	pdflatex main-diff
	pdflatex main-diff

clean:
	rm -rf *~ *.log *.aux *.blg *.bbl

# eof
